### ISSUE TITLE
sim fails to start in requirejs mode with assertions enabled

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gene-expression-basics#7]
Noted when running build-server.  Here's the console error in requirejs mode, with assertions enabled:

![screenshot_577](https://cloud.githubusercontent.com/assets/3046552/9320008/40123b8e-4512-11e5-8b90-ebd8d9c06f1a.png)

**Comment by pixelzoom** [comment]
This is still a problem as of 8/25/15 run of test-server.

**Comment by AshrafSharf** [comment]
The getScaleVector method of Matrix3 always returns positive value for the scales, even though
 the mvt uses inverted scaling for Y, so changing the assertion statement to check for absolute values. Please see the snippet from Matrix3

```Javascript
getScaleVector: function() {
      return new dot.Vector2(
        Math.sqrt( this.m00() * this.m00() + this.m10() * this.m10() ),
        Math.sqrt( this.m01() * this.m01() + this.m11() * this.m11() ) );
    }

After changing the assertion statement, the sim now starts.

**Comment by pixelzoom** [comment]
:+1: Closing.
