### ISSUE TITLE
fix string var names

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gene-expression-basics#9]
... that fail ESLint. See https://github.com/phetsims/chipper/issues/396#issuecomment-155566007.

**Comment by pixelzoom** [comment]
This is causing the sim to fail the build step in test-server.

**Comment by jbphet** [comment]
Fixed, sim is passing lint as of 2b733c51b42af5b6c8d8e9e09eb6f7d57414bd43, closing.
